"""initial

Revision ID: 7ea11ebf8b14
Revises: 
Create Date: 2026-06-05 00:16:54.262122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ea11ebf8b14'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario_sistema',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('nombre_completo', sa.String(length=160), nullable=False),
    sa.Column('correo_electronico', sa.String(length=160), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('ultimo_acceso', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuario_sistema', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuario_sistema_correo_electronico'), ['correo_electronico'], unique=True)
        batch_op.create_index(batch_op.f('ix_usuario_sistema_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_usuario_sistema_rol'), ['rol'], unique=False)
        batch_op.create_index(batch_op.f('ix_usuario_sistema_username'), ['username'], unique=True)

    op.create_table('bitacora_acceso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('fecha_hora', sa.DateTime(), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('accion', sa.String(length=80), nullable=False),
    sa.Column('detalle', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario_sistema.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bitacora_acceso', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bitacora_acceso_fecha_hora'), ['fecha_hora'], unique=False)
        batch_op.create_index(batch_op.f('ix_bitacora_acceso_usuario_id'), ['usuario_id'], unique=False)

    with op.batch_alter_table('alerta_pedido', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('alerta_pedido_id_alerta_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('alerta_pedido_id_pedido_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'alerta', ['id_alerta'], ['id_alerta'])
        batch_op.create_foreign_key(None, 'pedido', ['id_pedido'], ['id_pedido'])

    with op.batch_alter_table('compra', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('compra_id_proveedor_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'proveedor', ['id_proveedor'], ['id_proveedor'])

    with op.batch_alter_table('detalle_compra', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('detalle_compra_id_producto_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('detalle_compra_id_compra_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'compra', ['id_compra'], ['id_compra'])
        batch_op.create_foreign_key(None, 'producto', ['id_producto'], ['id_producto'])

    with op.batch_alter_table('detalle_factura', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('detalle_factura_id_pago_unico_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('detalle_factura_id_factura_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'pago_unico', ['id_pago_unico'], ['id_pago_unico'])
        batch_op.create_foreign_key(None, 'factura', ['id_factura'], ['id_factura'])

    with op.batch_alter_table('detalle_pedido', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_detalle_pedido_id_pedido'), ['id_pedido'], unique=False)
        batch_op.create_index(batch_op.f('ix_detalle_pedido_id_producto'), ['id_producto'], unique=False)
        batch_op.drop_constraint(batch_op.f('detalle_pedido_id_pedido_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('detalle_pedido_id_producto_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'pedido', ['id_pedido'], ['id_pedido'])
        batch_op.create_foreign_key(None, 'producto', ['id_producto'], ['id_producto'])

    with op.batch_alter_table('direccion_empleado', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('direccion_empleado_id_empleado_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'empleado', ['id_empleado'], ['id_empleado'])

    with op.batch_alter_table('direccion_minimarket', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_direccion_minimarket_zona'), ['zona'], unique=False)
        batch_op.drop_constraint(batch_op.f('direccion_minimarket_id_minimarket_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'minimarket', ['id_minimarket'], ['id_minimarket'])

    with op.batch_alter_table('direccion_restaurante', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_direccion_restaurante_zona'), ['zona'], unique=False)
        batch_op.drop_constraint(batch_op.f('direccion_restaurante_id_restaurante_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'restaurante', ['id_restaurante'], ['id_restaurante'])

    with op.batch_alter_table('direccion_usuario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_direccion_usuario_zona'), ['zona'], unique=False)
        batch_op.drop_constraint(batch_op.f('direccion_usuario_id_usuario_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuario', ['id_usuario'], ['id_usuario'])

    with op.batch_alter_table('empleado_pedido', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('empleado_pedido_id_empleado_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('empleado_pedido_id_pedido_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'empleado', ['id_empleado'], ['id_empleado'])
        batch_op.create_foreign_key(None, 'pedido', ['id_pedido'], ['id_pedido'])

    with op.batch_alter_table('entrega', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entrega_fecha_aceptacion'), ['fecha_aceptacion'], unique=False)
        batch_op.create_index(batch_op.f('ix_entrega_fecha_asignacion'), ['fecha_asignacion'], unique=False)
        batch_op.create_index(batch_op.f('ix_entrega_id_repartidor'), ['id_repartidor'], unique=False)
        batch_op.drop_constraint(batch_op.f('entrega_id_repartidor_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('entrega_id_seguimiento_entrega_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'repartidor', ['id_repartidor'], ['id_repartidor'])
        batch_op.create_foreign_key(None, 'seguimiento_entrega', ['id_seguimiento_entrega'], ['id_seguimiento_entrega'])

    with op.batch_alter_table('pago_unico', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pago_unico_fecha_pago'), ['fecha_pago'], unique=False)
        batch_op.create_index(batch_op.f('ix_pago_unico_id_pedido'), ['id_pedido'], unique=False)
        batch_op.create_index(batch_op.f('ix_pago_unico_monto'), ['monto'], unique=False)
        batch_op.drop_constraint(batch_op.f('pago_unico_id_pedido_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'pedido', ['id_pedido'], ['id_pedido'])

    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pedido_fecha_pedido'), ['fecha_pedido'], unique=False)
        batch_op.create_index(batch_op.f('ix_pedido_id_usuario'), ['id_usuario'], unique=False)
        batch_op.drop_constraint(batch_op.f('pedido_id_promocion_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('pedido_id_usuario_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuario', ['id_usuario'], ['id_usuario'])
        batch_op.create_foreign_key(None, 'promocion', ['id_promocion'], ['id_promocion'])

    with op.batch_alter_table('pedido_resena', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('pedido_resena_id_resena_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('pedido_resena_id_pedido_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'pedido', ['id_pedido'], ['id_pedido'])
        batch_op.create_foreign_key(None, 'resena', ['id_resena'], ['id_resena'])

    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_producto_nombre'), ['nombre'], unique=False)
        batch_op.drop_constraint(batch_op.f('producto_id_proveedor_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('producto_id_inventario_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'proveedor', ['id_proveedor'], ['id_proveedor'])
        batch_op.create_foreign_key(None, 'inventario', ['id_inventario'], ['id_inventario'])

    with op.batch_alter_table('producto_minimarket', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('producto_minimarket_id_minimarket_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('producto_minimarket_id_producto_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'minimarket', ['id_minimarket'], ['id_minimarket'])
        batch_op.create_foreign_key(None, 'producto', ['id_producto'], ['id_producto'])

    with op.batch_alter_table('producto_restaurante', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('producto_restaurante_id_producto_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('producto_restaurante_id_restaurante_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'restaurante', ['id_restaurante'], ['id_restaurante'])
        batch_op.create_foreign_key(None, 'producto', ['id_producto'], ['id_producto'])

    with op.batch_alter_table('repartidor', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_repartidor_disponibilidad'), ['disponibilidad'], unique=False)
        batch_op.create_index(batch_op.f('ix_repartidor_nombre'), ['nombre'], unique=False)

    with op.batch_alter_table('repartidor_pedido', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('repartidor_pedido_id_repartidor_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('repartidor_pedido_pedido_id_pedido_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'repartidor', ['id_repartidor'], ['id_repartidor'])
        batch_op.create_foreign_key(None, 'pedido', ['pedido_id_pedido'], ['id_pedido'])

    with op.batch_alter_table('resena', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resena_calificacion'), ['calificacion'], unique=False)

    with op.batch_alter_table('restaurante', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_restaurante_nombre'), ['nombre'], unique=False)
        batch_op.drop_constraint(batch_op.f('restaurante_id_menu_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'menu', ['id_menu'], ['id_menu'])

    with op.batch_alter_table('rol_usuario', schema=None) as batch_op:
        batch_op.drop_column('rol_usuariocol')

    with op.batch_alter_table('seguimiento_pedido', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_seguimiento_pedido_estado'), ['estado'], unique=False)
        batch_op.drop_constraint(batch_op.f('seguimiento_pedido_id_repartidor_pedido_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'repartidor_pedido', ['id_repartidor_pedido'], ['id_repartidor_pedido'])

    with op.batch_alter_table('soporte_chat', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('soporte_chat_usuario_id_usuario_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuario', ['usuario_id_usuario'], ['id_usuario'])

    with op.batch_alter_table('telefono_empleado', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('telefono_empleado_id_empleado_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'empleado', ['id_empleado'], ['id_empleado'])

    with op.batch_alter_table('telefono_proveedor', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('telefono_proveedor_id_proveedor_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'proveedor', ['id_proveedor'], ['id_proveedor'])

    with op.batch_alter_table('telefono_repartidor', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('telefono_repartidor_id_repartidor_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'repartidor', ['id_repartidor'], ['id_repartidor'])

    with op.batch_alter_table('telefono_restaurante', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('telefono_restaurante_id_restaurante_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'restaurante', ['id_restaurante'], ['id_restaurante'])

    with op.batch_alter_table('telefono_usuario', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('telefono_usuario_id_usuario_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuario', ['id_usuario'], ['id_usuario'])

    with op.batch_alter_table('tipo_promocion', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('tipo_promocion_id_promocion_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'promocion', ['id_promocion'], ['id_promocion'])

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('usuario_id_rol_usuario_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'rol_usuario', ['id_rol_usuario'], ['id_rol_usuario'])

    with op.batch_alter_table('vehiculo', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('vehiculo_id_repartidor_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'repartidor', ['id_repartidor'], ['id_repartidor'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehiculo', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('vehiculo_id_repartidor_fkey'), 'repartidor', ['id_repartidor'], ['id_repartidor'], onupdate='CASCADE')

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('usuario_id_rol_usuario_fkey'), 'rol_usuario', ['id_rol_usuario'], ['id_rol_usuario'], onupdate='CASCADE')

    with op.batch_alter_table('tipo_promocion', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('tipo_promocion_id_promocion_fkey'), 'promocion', ['id_promocion'], ['id_promocion'], onupdate='CASCADE')

    with op.batch_alter_table('telefono_usuario', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('telefono_usuario_id_usuario_fkey'), 'usuario', ['id_usuario'], ['id_usuario'], onupdate='CASCADE')

    with op.batch_alter_table('telefono_restaurante', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('telefono_restaurante_id_restaurante_fkey'), 'restaurante', ['id_restaurante'], ['id_restaurante'], onupdate='CASCADE')

    with op.batch_alter_table('telefono_repartidor', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('telefono_repartidor_id_repartidor_fkey'), 'repartidor', ['id_repartidor'], ['id_repartidor'], onupdate='CASCADE')

    with op.batch_alter_table('telefono_proveedor', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('telefono_proveedor_id_proveedor_fkey'), 'proveedor', ['id_proveedor'], ['id_proveedor'], onupdate='CASCADE')

    with op.batch_alter_table('telefono_empleado', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('telefono_empleado_id_empleado_fkey'), 'empleado', ['id_empleado'], ['id_empleado'], onupdate='CASCADE')

    with op.batch_alter_table('soporte_chat', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('soporte_chat_usuario_id_usuario_fkey'), 'usuario', ['usuario_id_usuario'], ['id_usuario'], onupdate='CASCADE')

    with op.batch_alter_table('seguimiento_pedido', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('seguimiento_pedido_id_repartidor_pedido_fkey'), 'repartidor_pedido', ['id_repartidor_pedido'], ['id_repartidor_pedido'], onupdate='CASCADE')
        batch_op.drop_index(batch_op.f('ix_seguimiento_pedido_estado'))

    with op.batch_alter_table('rol_usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rol_usuariocol', sa.VARCHAR(length=45), autoincrement=False, nullable=True))

    with op.batch_alter_table('restaurante', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('restaurante_id_menu_fkey'), 'menu', ['id_menu'], ['id_menu'], onupdate='CASCADE')
        batch_op.drop_index(batch_op.f('ix_restaurante_nombre'))

    with op.batch_alter_table('resena', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resena_calificacion'))

    with op.batch_alter_table('repartidor_pedido', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('repartidor_pedido_pedido_id_pedido_fkey'), 'pedido', ['pedido_id_pedido'], ['id_pedido'], onupdate='CASCADE')
        batch_op.create_foreign_key(batch_op.f('repartidor_pedido_id_repartidor_fkey'), 'repartidor', ['id_repartidor'], ['id_repartidor'], onupdate='CASCADE')

    with op.batch_alter_table('repartidor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_repartidor_nombre'))
        batch_op.drop_index(batch_op.f('ix_repartidor_disponibilidad'))

    with op.batch_alter_table('producto_restaurante', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('producto_restaurante_id_restaurante_fkey'), 'restaurante', ['id_restaurante'], ['id_restaurante'], onupdate='CASCADE')
        batch_op.create_foreign_key(batch_op.f('producto_restaurante_id_producto_fkey'), 'producto', ['id_producto'], ['id_producto'], onupdate='CASCADE')

    with op.batch_alter_table('producto_minimarket', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('producto_minimarket_id_producto_fkey'), 'producto', ['id_producto'], ['id_producto'], onupdate='CASCADE')
        batch_op.create_foreign_key(batch_op.f('producto_minimarket_id_minimarket_fkey'), 'minimarket', ['id_minimarket'], ['id_minimarket'], onupdate='CASCADE')

    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('producto_id_inventario_fkey'), 'inventario', ['id_inventario'], ['id_inventario'], onupdate='CASCADE')
        batch_op.create_foreign_key(batch_op.f('producto_id_proveedor_fkey'), 'proveedor', ['id_proveedor'], ['id_proveedor'], onupdate='CASCADE')
        batch_op.drop_index(batch_op.f('ix_producto_nombre'))

    with op.batch_alter_table('pedido_resena', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('pedido_resena_id_pedido_fkey'), 'pedido', ['id_pedido'], ['id_pedido'], onupdate='CASCADE')
        batch_op.create_foreign_key(batch_op.f('pedido_resena_id_resena_fkey'), 'resena', ['id_resena'], ['id_resena'], onupdate='CASCADE')

    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('pedido_id_usuario_fkey'), 'usuario', ['id_usuario'], ['id_usuario'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('pedido_id_promocion_fkey'), 'promocion', ['id_promocion'], ['id_promocion'], onupdate='CASCADE')
        batch_op.drop_index(batch_op.f('ix_pedido_id_usuario'))
        batch_op.drop_index(batch_op.f('ix_pedido_fecha_pedido'))

    with op.batch_alter_table('pago_unico', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('pago_unico_id_pedido_fkey'), 'pedido', ['id_pedido'], ['id_pedido'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_pago_unico_monto'))
        batch_op.drop_index(batch_op.f('ix_pago_unico_id_pedido'))
        batch_op.drop_index(batch_op.f('ix_pago_unico_fecha_pago'))

    with op.batch_alter_table('entrega', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('entrega_id_seguimiento_entrega_fkey'), 'seguimiento_entrega', ['id_seguimiento_entrega'], ['id_seguimiento_entrega'], onupdate='CASCADE')
        batch_op.create_foreign_key(batch_op.f('entrega_id_repartidor_fkey'), 'repartidor', ['id_repartidor'], ['id_repartidor'], onupdate='CASCADE')
        batch_op.drop_index(batch_op.f('ix_entrega_id_repartidor'))
        batch_op.drop_index(batch_op.f('ix_entrega_fecha_asignacion'))
        batch_op.drop_index(batch_op.f('ix_entrega_fecha_aceptacion'))

    with op.batch_alter_table('empleado_pedido', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('empleado_pedido_id_pedido_fkey'), 'pedido', ['id_pedido'], ['id_pedido'], onupdate='CASCADE')
        batch_op.create_foreign_key(batch_op.f('empleado_pedido_id_empleado_fkey'), 'empleado', ['id_empleado'], ['id_empleado'], onupdate='CASCADE')

    with op.batch_alter_table('direccion_usuario', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('direccion_usuario_id_usuario_fkey'), 'usuario', ['id_usuario'], ['id_usuario'], onupdate='CASCADE')
        batch_op.drop_index(batch_op.f('ix_direccion_usuario_zona'))

    with op.batch_alter_table('direccion_restaurante', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('direccion_restaurante_id_restaurante_fkey'), 'restaurante', ['id_restaurante'], ['id_restaurante'], onupdate='CASCADE')
        batch_op.drop_index(batch_op.f('ix_direccion_restaurante_zona'))

    with op.batch_alter_table('direccion_minimarket', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('direccion_minimarket_id_minimarket_fkey'), 'minimarket', ['id_minimarket'], ['id_minimarket'], onupdate='CASCADE')
        batch_op.drop_index(batch_op.f('ix_direccion_minimarket_zona'))

    with op.batch_alter_table('direccion_empleado', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('direccion_empleado_id_empleado_fkey'), 'empleado', ['id_empleado'], ['id_empleado'], onupdate='CASCADE')

    with op.batch_alter_table('detalle_pedido', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('detalle_pedido_id_producto_fkey'), 'producto', ['id_producto'], ['id_producto'], onupdate='CASCADE')
        batch_op.create_foreign_key(batch_op.f('detalle_pedido_id_pedido_fkey'), 'pedido', ['id_pedido'], ['id_pedido'], onupdate='CASCADE')
        batch_op.drop_index(batch_op.f('ix_detalle_pedido_id_producto'))
        batch_op.drop_index(batch_op.f('ix_detalle_pedido_id_pedido'))

    with op.batch_alter_table('detalle_factura', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('detalle_factura_id_factura_fkey'), 'factura', ['id_factura'], ['id_factura'], onupdate='CASCADE')
        batch_op.create_foreign_key(batch_op.f('detalle_factura_id_pago_unico_fkey'), 'pago_unico', ['id_pago_unico'], ['id_pago_unico'], onupdate='CASCADE')

    with op.batch_alter_table('detalle_compra', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('detalle_compra_id_compra_fkey'), 'compra', ['id_compra'], ['id_compra'], onupdate='CASCADE')
        batch_op.create_foreign_key(batch_op.f('detalle_compra_id_producto_fkey'), 'producto', ['id_producto'], ['id_producto'], onupdate='CASCADE')

    with op.batch_alter_table('compra', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('compra_id_proveedor_fkey'), 'proveedor', ['id_proveedor'], ['id_proveedor'], onupdate='CASCADE')

    with op.batch_alter_table('alerta_pedido', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('alerta_pedido_id_pedido_fkey'), 'pedido', ['id_pedido'], ['id_pedido'], onupdate='CASCADE')
        batch_op.create_foreign_key(batch_op.f('alerta_pedido_id_alerta_fkey'), 'alerta', ['id_alerta'], ['id_alerta'], onupdate='CASCADE')

    with op.batch_alter_table('bitacora_acceso', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bitacora_acceso_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_bitacora_acceso_fecha_hora'))

    op.drop_table('bitacora_acceso')
    with op.batch_alter_table('usuario_sistema', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuario_sistema_username'))
        batch_op.drop_index(batch_op.f('ix_usuario_sistema_rol'))
        batch_op.drop_index(batch_op.f('ix_usuario_sistema_estado'))
        batch_op.drop_index(batch_op.f('ix_usuario_sistema_correo_electronico'))

    op.drop_table('usuario_sistema')
    # ### end Alembic commands ###
